# Generated by Django 5.0.3 on 2024-11-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comment_activity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.ticket'),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='Activity_application',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='Assignment_application',
        ),
    ]
